#!/bin/bash


#prüfen ob der prtg-Order bereits vorhanden ist 

check1=$(ls -al /var/prtg/ 2>/dev/null | grep 'scripts' | wc -l)

if [[ "$check1" == "1" ]];then
#	echo "Ordnerstruktur bereits da"
	next1=1
else
	mkdir -p /var/prtg/scripts
	check1=$(ls -al /var/prtg/ 2>/dev/null | grep 'scripts' | wc -l)

	if [[ "$check1" == "1" ]];then
#		echo "Ordnerstruktur angelegt"
		next1=1
	else

		echo ""
#		echo "Ordnerstruktur anlegen fehlgeschlagen"
	fi
fi




#------------------------
#prüfen ob der update-Script bereits-vorhanden ist



check2=$(ls -al /var/prtg/scripts 2>/dev/null| grep 'update-check' | wc -l )


if [[ "$next1" == "1" ]]; then

	if [[ "$check2" == "1" ]];then
#		echo "update-skript bereits vorhanden"
		next2=1
	else
		cp /root/mth-script-master/mg-prtg-update/update-check /var/prtg/scripts/update-check  2>/dev/null
		check2=$(ls -al /var/prtg/scripts 2>/dev/null | grep 'update-check' | wc -l )
		if [[ "$check2" == "1" ]];then
#			echo "Update-skript wurde verschoben"
			next2=1
		else
			echo ""
			echo "Update-skript verschieben fehlgeschlagenn"
		fi
	fi
fi

#------------------------

check3=$(ls -al /var/prtg/scripts/update-check 2>/dev/null| grep 'rwxr-xr-x' | wc -l )

if [[ "$next2" == "1" ]]; then

	if [[ "$check3" == "1" ]];then
#	        echo "Skript Berechtigung bereits vorhanden"
		next3=1
		echo "success"
	else
		chmod 755  /var/prtg/scripts/update-check
		check3=$(ls -al /var/prtg/scripts/update-check 2>/dev/null | grep 'rwxr-xr-x' | wc -l )

		if [[ "$check3" == "1" ]];then
#		 	echo "Skript wurde ausführbar gemacht"
			echo "success"
			next3=1
		else
			echo ""
#			echo "Update-Skript ausführbar machen. fehlgeschlagen "
		fi
	fi
fi


#echo "next3=$next3"


#------------------------
#Remove old Files

check4=$(ls -al /root/ 2>/dev/null |grep 'master.zip\|mth-script-master' |wc -l)
#echo "check4 = $check4"

if [[ "$next3" == "1" ]];then

	if  [[ "$check4" == "0" ]];then
#		echo "Dateien bereits gelöscht"
		next4=1

	else
		rm -fr /root/master.zip
		rm -fr /root/mth-script-master

		check4=$(ls -al /root/ 2>/dev/null |grep 'master.zip\|mth-script-master' |wc -l)
			
		if  [[ "$check4" == "0" ]];then
#			echo "Dateien wurden gelöscht"
			next4=1
		else
			echo ""
#			echo "Datein Löschen Fehgeschlagen"
		fi
	fi 
fi 























